name: yatra_ai

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.12.1
  image_picker: ^1.2.3
  http: ^1.6.0
  google_fonts: ^9.0.0
  geolocator: ^14.1.1
  maplibre_gl: ^0.27.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/